# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: findloc_dev
  host: localhost
  pool: 5
  username:	postgres
  password: root


test:
  adapter: postgresql
  encoding: unicode
  database: findloc_test
  host: localhost
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: findloc_prod
  host: localhost
  pool: 5
  username: postgres
  password: root
